name: Update with the latest base16-project colorschemes
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # https://crontab.guru/every-week

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install pybase16
        run: pip install pybase16-builder
      - name: Fetch the repository code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
      - name: Run make
        run: make
      - name: Commit the changes, if any
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update with the latest base16-project colorschemes
          branch: ${{ github.head_ref }}
          commit_user_name: base16-project-bot
          commit_user_email: base16themeproject@proton.me
          commit_author: base16-project-bot <base16themeproject@proton.me>
